language: node_js

node_js:
  - 6.17.1
  - 8.16.0
  - 10.16.0

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev' ]

sudo: false

install:
- npm install

script:
- npm test

